# Generated by Django 5.0.2 on 2023-09-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0002_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
